// Code generated by Ginx protocolgen; DO NOT EDIT.
// Schema SHA-256: 26ebcae85286d911efe8f6b0df880a006af49aed581f623d3028092d5be467f5

package protocol

import "encoding/json"

const SchemaVersion uint32 = 1

const ProtocolVersion uint32 = 1

const MsgAuthenticate uint32 = 1001

type AuthenticateRequest struct {
	Token string `json:"token"`
}

type AuthenticateResponse struct {
	Code string           `json:"code"`
	Data *json.RawMessage `json:"data,omitempty"`
}

const MsgHeartbeat uint32 = 1002

type HeartbeatRequest struct{}

type HeartbeatResponse struct {
	Code string           `json:"code"`
	Data *json.RawMessage `json:"data,omitempty"`
}

const MsgJoinRoom uint32 = 2001

type JoinRoomRequest struct {
	RoomID uint32 `json:"room_id"`
}

type JoinRoomResponse struct {
	Code string           `json:"code"`
	Data *json.RawMessage `json:"data,omitempty"`
}

const MsgLeaveRoom uint32 = 2002

type LeaveRoomRequest struct{}

type LeaveRoomResponse struct {
	Code string           `json:"code"`
	Data *json.RawMessage `json:"data,omitempty"`
}

const MsgProgress uint32 = 3001

type ProgressRequest struct{}

type ProgressResponse struct {
	Code string           `json:"code"`
	Data *json.RawMessage `json:"data,omitempty"`
}

const MsgStarterReward uint32 = 3002

type StarterRewardRequest struct{}

type StarterRewardResponse struct {
	Code string           `json:"code"`
	Data *json.RawMessage `json:"data,omitempty"`
}

const MsgUseItem uint32 = 3003

type UseItemRequest struct {
	ItemID string `json:"item_id"`
}

type UseItemResponse struct {
	Code string           `json:"code"`
	Data *json.RawMessage `json:"data,omitempty"`
}
