# Code generated by Ginx protocolgen; DO NOT EDIT.
# Schema SHA-256: 26ebcae85286d911efe8f6b0df880a006af49aed581f623d3028092d5be467f5

SCHEMA_VERSION = 1
PROTOCOL_VERSION = 1

MsgAuthenticate = 1001
MsgHeartbeat = 1002
MsgJoinRoom = 2001
MsgLeaveRoom = 2002
MsgProgress = 3001
MsgStarterReward = 3002
MsgUseItem = 3003
