// Code generated by Ginx protocolgen; DO NOT EDIT.
// Schema SHA-256: 26ebcae85286d911efe8f6b0df880a006af49aed581f623d3028092d5be467f5

namespace Ginx.Examples.GameApp
{
    public static class ProtocolIds
    {
        public const uint SchemaVersion = 1u;
        public const uint ProtocolVersion = 1u;
        public const uint MsgAuthenticate = 1001u;
        public const uint MsgHeartbeat = 1002u;
        public const uint MsgJoinRoom = 2001u;
        public const uint MsgLeaveRoom = 2002u;
        public const uint MsgProgress = 3001u;
        public const uint MsgStarterReward = 3002u;
        public const uint MsgUseItem = 3003u;
    }
}
