#!/usr/bin/env python3
"""Ginx 构建期协议生成器，仅使用 Python 3.10+ 标准库。"""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import os
from pathlib import Path
import re
import sys
import tempfile


ROOT = Path(__file__).resolve().parents[2]
GENERATOR = "Ginx protocolgen"
GO_MARKER = "// Code generated by Ginx protocolgen; DO NOT EDIT."
PY_MARKER = "# Code generated by Ginx protocolgen; DO NOT EDIT."
MD_MARKER = "<!-- Code generated by Ginx protocolgen; DO NOT EDIT. -->"
TYPES = {"string", "bool", "int32", "uint32", "int64", "uint64", "float64", "bytes", "json"}
GO_KEYWORDS = set("break default func interface select case defer go map struct chan else goto package switch const fallthrough if range type continue for import return var main".split())
INITIALISMS = {"id", "ip", "url", "http", "tcp", "api", "json", "uuid"}
MAX_SCHEMA_BYTES = 2 * 1024 * 1024


class SchemaError(ValueError):
    """定义、兼容性或输出路径不满足工具契约。"""


def require(condition: bool, message: str) -> None:
    if not condition:
        raise SchemaError(message)


def object_keys(value, required: set[str], optional: set[str], label: str) -> None:
    require(isinstance(value, dict), f"{label}: expected object")
    missing, extra = required - value.keys(), value.keys() - required - optional
    require(not missing, f"{label}: missing keys {sorted(missing)}")
    require(not extra, f"{label}: unknown keys {sorted(extra)}")


def integer(value, low: int, high: int, label: str) -> None:
    require(type(value) is int and low <= value <= high, f"{label}: expected integer {low}..{high}")


def identifier(value, pattern: str, label: str) -> None:
    require(isinstance(value, str) and len(value) <= 100 and re.fullmatch(pattern, value) is not None,
            f"{label}: invalid identifier")


def description(value, label: str) -> str:
    require(isinstance(value, str) and len(value) <= 1000, f"{label}: expected text up to 1000 characters")
    require(all(ord(c) >= 32 and not 127 <= ord(c) <= 159 and not 0xD800 <= ord(c) <= 0xDFFF for c in value),
            f"{label}: control characters are not allowed")
    return value


def go_field(name: str) -> str:
    return "".join(word.upper() if word in INITIALISMS else word.capitalize() for word in name.split("_"))


def validate_fields(value, label: str) -> list[dict]:
    require(isinstance(value, list) and len(value) <= 128, f"{label}: expected array of at most 128 fields")
    result, names, symbols = [], set(), set()
    for index, field in enumerate(value):
        loc = f"{label}[{index}]"
        object_keys(field, {"name", "type"}, {"optional", "description"}, loc)
        name, kind = field["name"], field["type"]
        identifier(name, r"[a-z][a-z0-9]*(?:_[a-z][a-z0-9]*)*", f"{loc}.name")
        require(name not in names, f"{loc}: duplicate field {name}")
        symbol = go_field(name)
        require(symbol not in symbols, f"{loc}: Go field collision {symbol}")
        names.add(name)
        symbols.add(symbol)
        require(isinstance(kind, str), f"{loc}.type: expected string")
        base = kind[2:] if kind.startswith("[]") else kind
        require(base in TYPES, f"{loc}.type: unsupported type {kind}")
        optional = field.get("optional", False)
        require(type(optional) is bool, f"{loc}.optional: expected boolean")
        result.append({"name": name, "type": kind, "optional": optional,
                       "description": description(field.get("description", ""), f"{loc}.description")})
    return sorted(result, key=lambda f: f["name"])


def validate_schema(value) -> dict:
    required = {"schema_version", "protocol_version", "go_package", "csharp_namespace", "encoding", "messages"}
    object_keys(value, required, set(), "schema")
    integer(value["schema_version"], 1, 1, "schema_version")
    integer(value["protocol_version"], 1, 0xFFFFFFFF, "protocol_version")
    identifier(value["go_package"], r"[a-z][a-z0-9_]*", "go_package")
    require(value["go_package"] not in GO_KEYWORDS, "go_package: reserved package name")
    identifier(value["csharp_namespace"], r"[A-Z][A-Za-z0-9]*(?:\.[A-Z][A-Za-z0-9]*)*", "csharp_namespace")
    require(value["encoding"] == "json", "encoding: only json is supported")
    messages = value["messages"]
    require(isinstance(messages, list) and 1 <= len(messages) <= 4096, "messages: expected 1..4096 messages")
    names, ids, symbols, result = set(), set(), {"SchemaVersion", "ProtocolVersion"}, []
    for index, msg in enumerate(messages):
        loc = f"messages[{index}]"
        object_keys(msg, {"name", "id", "request", "response"}, {"description"}, loc)
        name, msg_id = msg["name"], msg["id"]
        identifier(name, r"[A-Z][A-Za-z0-9]*", f"{loc}.name")
        integer(msg_id, 0, 0xFFFFFFFF, f"{loc}.id")
        require(name not in names, f"{loc}: duplicate message name {name}")
        require(msg_id not in ids, f"{loc}: duplicate message ID {msg_id}")
        names.add(name)
        ids.add(msg_id)
        for symbol in ("Msg" + name, name + "Request", name + "Response"):
            require(symbol not in symbols, f"{loc}: generated Go symbol collision {symbol}")
            symbols.add(symbol)
        result.append({"name": name, "id": msg_id,
                       "description": description(msg.get("description", ""), f"{loc}.description"),
                       "request": validate_fields(msg["request"], f"{loc}.request"),
                       "response": validate_fields(msg["response"], f"{loc}.response")})
    return {"schema_version": value["schema_version"], "protocol_version": value["protocol_version"],
            "go_package": value["go_package"], "csharp_namespace": value["csharp_namespace"],
            "encoding": value["encoding"], "messages": sorted(result, key=lambda m: m["id"])}


def unique_object(pairs):
    value = {}
    for key, item in pairs:
        require(key not in value, f"duplicate JSON key: {key}")
        value[key] = item
    return value


def reject_constant(value):
    raise SchemaError(f"non-JSON numeric constant: {value}")


def load_schema(path: Path) -> dict:
    with path.open("rb") as stream:
        raw = stream.read(MAX_SCHEMA_BYTES + 1)
    require(len(raw) <= MAX_SCHEMA_BYTES, "schema exceeds 2 MiB")
    value = json.loads(raw.decode("utf-8-sig"), object_pairs_hook=unique_object, parse_constant=reject_constant)
    if isinstance(value, dict) and "generator" in value:
        object_keys(value, {"generator", "schema"}, set(), "lock")
        require(value["generator"] == GENERATOR, "unknown lock generator")
        value = value["schema"]
    return validate_schema(value)


def wire_shape(message: dict) -> dict:
    return {side: [(f["name"], f["type"], f["optional"]) for f in message[side]] for side in ("request", "response")}


def check_compatibility(current: dict, baseline: dict) -> None:
    """保守检查：老消息的形状完全不变，只允许递增版本后新增消息。"""
    require(current["protocol_version"] >= baseline["protocol_version"], "protocol_version cannot decrease")
    for key in ("go_package", "csharp_namespace", "encoding"):
        require(current[key] == baseline[key], f"incompatible change: {key}")
    current_by_name = {m["name"]: m for m in current["messages"]}
    for old in baseline["messages"]:
        name = old["name"]
        require(name in current_by_name, f"incompatible removal/rename: {name}")
        new = current_by_name[name]
        require(new["id"] == old["id"], f"incompatible message ID change: {name}")
        require(wire_shape(new) == wire_shape(old), f"incompatible field change: {name}")
    if len(current["messages"]) > len(baseline["messages"]):
        require(current["protocol_version"] > baseline["protocol_version"], "new messages require a protocol_version increase")


def go_type(kind: str) -> str:
    if kind.startswith("[]"):
        return "[]" + go_type(kind[2:])
    return {"bytes": "[]byte", "json": "json.RawMessage"}.get(kind, kind)


def render_go(schema: dict, digest: str) -> str:
    lines = [GO_MARKER, "// Schema SHA-256: " + digest, "", "package " + schema["go_package"], ""]
    if any(f["type"].removeprefix("[]") == "json" for m in schema["messages"] for side in ("request", "response") for f in m[side]):
        lines += ['import "encoding/json"', ""]
    lines += [f'const SchemaVersion uint32 = {schema["schema_version"]}', "",
              f'const ProtocolVersion uint32 = {schema["protocol_version"]}', ""]
    for msg in schema["messages"]:
        lines += [f'const Msg{msg["name"]} uint32 = {msg["id"]}', ""]
        for side in ("request", "response"):
            struct_name = msg["name"] + side.capitalize()
            fields = msg[side]
            if not fields:
                lines += [f"type {struct_name} struct{{}}", ""]
                continue
            columns = [(go_field(f["name"]), ("*" if f["optional"] else "") + go_type(f["type"]),
                        f'`json:"{f["name"]}{",omitempty" if f["optional"] else ""}"`') for f in fields]
            name_width = max(len(c[0]) for c in columns)
            type_width = max(len(c[1]) for c in columns)
            lines.append(f"type {struct_name} struct {{")
            lines.extend(f"\t{name:<{name_width}} {kind:<{type_width}} {tag}" for name, kind, tag in columns)
            lines += ["}", ""]
    return "\n".join(lines)


def md(value: str) -> str:
    return html.escape(value, quote=False).replace("\\", "\\\\").replace("|", "\\|").replace("`", "&#96;")


def render(schema: dict) -> dict[str, str]:
    canonical = json.dumps(schema, ensure_ascii=True, sort_keys=True, separators=(",", ":"))
    digest = hashlib.sha256(canonical.encode("utf-8")).hexdigest()
    py = [PY_MARKER, "# Schema SHA-256: " + digest, "",
          f'SCHEMA_VERSION = {schema["schema_version"]}', f'PROTOCOL_VERSION = {schema["protocol_version"]}', ""]
    cs = [GO_MARKER, "// Schema SHA-256: " + digest, "", "namespace " + schema["csharp_namespace"], "{",
          "    public static class ProtocolIds", "    {", f'        public const uint SchemaVersion = {schema["schema_version"]}u;',
          f'        public const uint ProtocolVersion = {schema["protocol_version"]}u;']
    doc = [MD_MARKER, "", "# Protocol reference", "", f'Protocol version: {schema["protocol_version"]}. Schema format: 1.', "",
           "Framing: DataLen uint32 LE + MsgID uint32 LE + DataLen bytes of UTF-8 JSON.",
           "DataLen excludes the 8-byte header. ProtocolVersion is metadata; it is not added to the wire.",
           "Request and response use the same message ID. No automatic validation, routing or serialization is generated.", "",
           "| ID | Message | Description |", "| --- | --- | --- |"]
    for msg in schema["messages"]:
        py.append(f'Msg{msg["name"]} = {msg["id"]}')
        cs.append(f'        public const uint Msg{msg["name"]} = {msg["id"]}u;')
        doc.append(f'| {msg["id"]} | {msg["name"]} | {md(msg["description"])} |')
    for msg in schema["messages"]:
        for side in ("request", "response"):
            doc += ["", f'## {msg["name"]}{side.capitalize()}', ""]
            if not msg[side]:
                doc.append("Empty JSON object (`{}`).")
                continue
            doc += ["| Field | Type | Optional | Description |", "| --- | --- | --- | --- |"]
            for f in msg[side]:
                doc.append(f'| `{f["name"]}` | `{f["type"]}` | {str(f["optional"]).lower()} | {md(f["description"])} |')
    cs += ["    }", "}"]
    return {"protocol.gen.go": render_go(schema, digest), "protocol_gen.py": "\n".join(py) + "\n",
            "ProtocolIds.g.cs": "\n".join(cs) + "\n", "protocol.md": "\n".join(doc) + "\n",
            "protocol.lock.json": json.dumps({"generator": GENERATOR, "schema": schema}, ensure_ascii=True, indent=2) + "\n"}


def owned(name: str, text: str) -> bool:
    if name == "protocol.lock.json":
        try:
            value = json.loads(text)
            return isinstance(value, dict) and value.get("generator") == GENERATOR
        except ValueError:
            return False
    marker = PY_MARKER if name.endswith(".py") else MD_MARKER if name.endswith(".md") else GO_MARKER
    return text.startswith(marker + "\n")


def output_files(out: Path, files: dict[str, str], check: bool, protected: list[Path]) -> list[str]:
    """先检查所有目标；单文件原子替换，不删除目录中的其他文件。"""
    out = out.absolute()
    require(not any(p.is_symlink() for p in (out, *out.parents)), "output directory must not traverse a symlink")
    require(not out.exists() or out.is_dir(), "output path is not a directory")
    changes = []
    for name, expected in files.items():
        path = out / name
        require(not path.is_symlink(), f"refusing symlink output: {path}")
        require(check or path.resolve() not in protected, f"output would overwrite input: {path}")
        actual = path.read_text(encoding="utf-8") if path.exists() else None
        if actual != expected:
            if not check and actual is not None:
                require(owned(name, actual), f"refusing to overwrite non-generated file: {path}")
            changes.append(name)
    if check:
        return changes
    if changes:
        out.mkdir(parents=True, exist_ok=True)
    for name in changes:
        temporary = None
        try:
            with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", newline="\n", dir=out, prefix=".protocolgen-", delete=False) as stream:
                temporary = Path(stream.name)
                stream.write(files[name])
            os.replace(temporary, out / name)
        finally:
            if temporary is not None and temporary.exists():
                temporary.unlink()
    return changes


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--schema", type=Path, help="JSON definition (default: repository schema/gameapp.json)")
    parser.add_argument("--out", type=Path, help="output directory; required for custom schemas")
    parser.add_argument("--baseline", type=Path, help="previous schema or protocol.lock.json for conservative compatibility checks")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="report missing/outdated artifacts without writing")
    mode.add_argument("--validate", action="store_true", help="validate schema and optional baseline only")
    args = parser.parse_args(argv)
    schema_path = args.schema or ROOT / "schema/gameapp.json"
    try:
        require(args.schema is None or args.out is not None or args.validate, "--out is required with a custom --schema")
        schema = load_schema(schema_path)
        protected = [schema_path.resolve()]
        if args.baseline:
            check_compatibility(schema, load_schema(args.baseline))
            protected.append(args.baseline.resolve())
        if args.validate:
            print(f"VALID: {len(schema['messages'])} messages, protocol version {schema['protocol_version']}")
            return 0
        out = args.out or ROOT / "examples/gameapp/protocol"
        changed = output_files(out, render(schema), args.check, protected)
        if args.check and changed:
            print("OUTDATED: " + ", ".join(changed), file=sys.stderr)
            return 1
        print("OK: artifacts are current" if args.check else f"OK: wrote {len(changed)} artifacts")
        return 0
    except (SchemaError, OSError, ValueError, RecursionError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
